###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

 {
    "dni": "89012345",
    "firstName": "Miguel",
    "lastName": "Santos",
    "email": "miguel.santos@gmail.com",
    "phoneNumber": "1234567899",
    "birthDate": "1987-10-30"
  }

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/672e891fe746244c7285cf2c HTTP/1.1

###
DELETE http://localhost:9000/api/users/672e88ace746244c7285cf28 HTTP/1.1

###
PUT http://localhost:9000/api/users/672e891fe746244c7285cf2c HTTP/1.1
Content-Type: application/json

{
  "dni": "123458878",
  "firstName": "Nolberto",
  "lastName": "Sumaran Pimentel",
  "email": "luis.sumaran@gmail.com",
  "phoneNumber": "1234567890",
  "birthDate": "1990-01-01T00:00:00.000Z"
}
